### ISSUE TITLE
Cant launch the Exe

### ISSUE THREAD

**Issue by okkward** [MrJPGames/NDS2Hiya#1] opened 2020-11-25 21:14 UTC
Everytime i open it, windows gives me a error that says that the path specified dosent exist and then the .exe deletes itself. Please help

**Comment by MrJPGames** [comment] 2020-11-25 21:17
I am unable to reproduce this error.

Could you send a screenshot of the error, so I can have all information that is provided.

My best guess at this point would be a lack of .NET framework but the error should allow me to tell, and hopefully provide instructions on how to fix the issue/allow me to fix a potential bug causing the issue.

**Comment by okkward** [comment] 2020-11-25 21:24
how can i send a video?

**Comment by MrJPGames** [comment] 2020-11-25 21:26
You can drag and drop the file into the textbox and it should attach it. Though if it's only a single error I believe a picture should be enough.

**Comment by okkward** [comment] 2020-11-25 21:28
nah it said id soesnt support mp4
https://youtu.be/tAiThRiKR98

**Comment by MrJPGames** [comment] 2020-11-25 21:37
I'm sorry this is a generic Windows error. This is not a bug or fault in the program. Instead there is something configured incorrectly with your file/folder access permission (admin does not have absolute rights in some cases).

As I would have to know specifics of your device and setup to assist you with this issue I can sadly not help you.

One common cause might me Anti-Virus which can remove files before Windows gets the chance to actually execute them. In this case you would have to add a special case for this program. Some anti-virus software marks unknown software as dangerous even if it is not an actual virus (you can check the code if you really wanted to).

Other than that, Google is your friend.

I hope you figure out what is causing this issue! But as I cannot really assist, nor is it a issue with the actual program itself I will close this issue.

**Closed as completed by MrJPGames** 2020-11-25 21:37 UTC

**Comment by okkward** [comment] 2020-11-26 19:13
I have fixed this issue, one of my Dads reccomended anti viruses was being Intrusive.
